### ISSUE TITLE
Enable GitHub Discussions.

### ISSUE THREAD

**Issue by flatheadmill** [lainio/err2#2]
I have some general questions about how to use `err2` and I don't want to junk up your issues with Go newbie questions. Perhaps you could enable GitHub Discussions or else add a "Getting Help" or "Community" section to the `README.md` where you could link to your preferred Q&A forum.

**Comment by lainio** [comment]
Hi @flatheadmill, and thanks for the issue. Excellent point. I'll look at what I can do. In the meanwhile, you can send me a direct email at harlain@gmail.com.

And I'm sorry for my late reply. The project has been in experimental mode until Go's generics. Now, err2 has the proper API. So, I could say that I'll start the project maintenance right now 😅
